version: "3.8"
name: task-manager

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    healthcheck:
      test: ["CMD", "php", "artisan", "config:show", "app.key"]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 5s
    user: "${UID:-1000}:${GID:-1000}"
    working_dir: /app
    volumes:
      - ./:/app
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - task_manager_shared
    environment:
      - NPM_CONFIG_CACHE=/app/.npm

  nginx:
    image: nginx:stable-alpine
    ports:
      - "9005:80"
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - task_manager_shared
  
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_manager
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - task_manager_shared

networks:
  task_manager_shared:
    name: task_manager_shared  

volumes:
  db:
    driver: local
  node_modules: