version: "3.7"

services:
  mailpit:
    image: axllent/mailpit
    environment:
      MP_DATA_FILE: /data/mailpit.db
      MP_UI_BIND_ADDR: 0.0.0.0:8025 
      MP_SMTP_AUTH_ACCEPT_ANY: 'true'
      MP_SMTP_AUTH_ALLOW_INSECURE: 'true'
      TZ: America/Sao_Paulo
    ports:
      - "8025:8025" 
      - "1025:1025"
    volumes:
      - ./data:/data:delegated
    networks:
      - task_manager_shared

networks:
  task_manager_shared:
    name: task_manager_shared